<?php

return [
    'DATE_FULL_FORMAT_DISPLAY' => env('DATE_FULL_FORMAT_DISPLAY'),
    'DATE_FORMAT_DISPLAY' => env('DATE_FORMAT_DISPLAY'),
    'LANGUAGE_DEFAULT' => 'vn',
    'DOMAIN_NAME' => env('DOMAIN_NAME'),
    'GOOGLE_MAP_API_KEY' => env('GOOGLE_MAP_API_KEY')
];